labseu2-anonymous-team-feedback/FE

.hound.yml
README.md

Integrate Hound for lint checking

integrate hound

---

.eslintrc.js
package.json
src/components/auth/signup/Signup.jsx
src/graphql/mutations.js

Signup functionality

---

package.json
src/components/survey/CreateSurvey.jsx
src/components/survey/Question.jsx
src/components/survey/SurveyStyles.js
src/graphql/mutations.js
src/index.jsx

Implement create survey feature. This is a work in progress PR. When the backend implements the ability to add questions, the code on this PR would have to be slightly modified accordingly so that questions can be created.
Tests are yet to be updated.

Implement create survey feature

---

src/components/survey/Question.jsx
src/components/survey/SurveyStyles.js

Make survey responsive

---

src/components/survey/CreateSurvey.jsx
src/components/survey/Question.jsx
src/graphql/mutations.js

Creates a survey along with the questions under that survey.

Implement create survey feature with questions

---

src/App.jsx
src/components/auth/resetPassword/ResetPassword.jsx
src/components/auth/resetPassword/ResetPasswordConfirmation.jsx
src/components/auth/resetPassword/StyledResetPassword.js

Add reset password and resed password confirmation pages

---

src/App.jsx
src/components/auth/resetPassword/NewPassword.jsx
src/components/auth/resetPassword/StyledResetPassword.js

Design a form that allows user to enter their new value of password to be updated.

Create a form for user to update/reset their password with a new password

---

README.md
package.json
src/components/auth/siginin/Signin.jsx
src/components/auth/siginin/StyledSignin.js
src/components/auth/signup/Signup.jsx
src/components/auth/signup/StyledSignup.js
src/graphql/mutations.js

Add the ability to register and login with google.

Google authentication

---

src/App.jsx
src/components/common/Navigation.jsx
src/graphql/mutations.js

Implement verify user email

---

src/components/auth/resetPassword/NewPassword.jsx
src/components/auth/resetPassword/ResetPassword.jsx
src/components/auth/siginin/Signin.jsx
src/components/auth/signup/Signup.jsx
src/components/common/TextInput.jsx
src/components/survey/CreateSurvey.jsx

Create a reusable text input component for all inputs of type `text`, `password` and `email`.

Create a reusable text input component 

---

src/components/auth/signup/Signup.jsx

Fix alert showing on google signing

Fix alert showing on google signing

---

src/components/auth/siginin/Signin.jsx
src/components/auth/signup/Signup.jsx
src/components/common/OptionSelect.jsx
src/components/common/TextArea.jsx
src/components/common/TextInput.jsx
src/components/survey/Question.jsx

Create a reusable text area component.

Reusable text area component

---

src/App.jsx
src/components/auth/signup/StyledSignup.js
src/components/common/NavBarStyles.js
src/components/common/Navigation.jsx
src/components/common/OptionSelect.jsx
src/components/common/TextInput.jsx
src/components/survey/CreateSurvey.jsx
src/components/survey/SurveyStyles.js

Improve on the responsiveness of the site on mobile and tablet devices.

Improve on responsiveness of the application

---

README.md

Add more libraries to readme

---

src/components/auth/resetPassword/NewPassword.jsx
src/components/auth/signup/Signup.jsx
src/components/common/NavBarStyles.js
src/components/common/Navigation.jsx
src/components/survey/Question.jsx
src/components/survey/SurveyStyles.js

Fix the issues arising from the first QA

Incorporate QA feedback 1

---

src/components/auth/resetPassword/NewPassword.jsx
src/components/auth/resetPassword/ResetPassword.jsx
src/components/auth/siginin/Signin.jsx
src/components/auth/signup/Signup.jsx
src/components/common/NavBarStyles.js
src/components/common/Navigation.jsx
src/components/survey/CreateSurvey.jsx
src/components/survey/SurveyStyles.js
src/index.css

Implement feedback from second QA.

Incorporate second QA feedback

---

src/components/common/NavBarStyles.js
src/components/common/Navigation.jsx
src/index.css

Make the logo slightly bigger on mobile. Soften the blackness on the titles.

Fix avatar layout and logo size

---

src/components/survey/Survey.jsx

Make share link URL for surveys dynamic

Bugfix url link

---

src/components/common/Navigation.jsx

debug navbar

---

src/components/common/Navigation.jsx

Fix navbar

---

src/Provider.jsx
src/assets/icons/icons.js
src/components/common/Navigation.jsx
src/components/dashboard/layouts/DashboardLayoutStyles.js
src/components/dashboard/layouts/Sidebar.jsx

Add a log out link to the sidebar for mobile devices.

Display logout link on sidebar on mobile

---

src/components/common/Navigation.jsx
src/components/dashboard/layouts/DashboardLayoutStyles.js
src/components/dashboard/layouts/Sidebar.jsx

Reduce the width of the dashboard sidebar on mobile devices.

Make the dashboard sidebar width less wide

---

src/components/survey/CreateSurvey.jsx

Fix issue with newly created survey requiring a refresh to be displayed.

Fix survey refresh issue

---

package.json
src/App.jsx
src/components/dashboard/layouts/__snapshots__/Sidebar.test.jsx.snap
src/components/response/Chart.jsx
src/components/response/Chart.test.jsx
src/components/response/Response.jsx
src/components/response/Response.test.jsx
src/components/response/ResultSort.jsx
src/components/response/ResultSort.test.jsx
src/components/response/__snapshots__/Chart.test.jsx.snap
src/components/response/__snapshots__/Response.test.jsx.snap
src/components/response/__snapshots__/ResultSort.test.jsx.snap
src/components/survey/__snapshots__/CreateSurvey.test.jsx.snap

Write tests for response component

Chore test response comp

---

src/components/common/NavBarStyles.js

Change bars color to the main color

Change bars color to the main color

---

src/components/dashboard/DashboardStyles.js
src/components/survey/CreateSurvey.jsx

Remove hover color from dashboard buttons to make design more unified

Remove hover color from dashboard buttons to make design more unified

---

src/components/survey/CreateSurvey.jsx

Fix issue with the newly created survey.

Fix survey refresh issue again

---

src/components/dashboard/layouts/DashboardLayoutStyles.js
src/components/response/Chart.jsx
src/components/response/Response.jsx
src/components/response/ResultSort.jsx

Improve results page

---

src/components/feedback/Feedback.jsx
src/graphql/queries.js
src/index.jsx

The owner of a survey should not be able to take their own survey.

Reject owner's feedback

---

src/components/response/Chart.jsx
src/components/response/Response.jsx

Tweak results

---

src/components/dashboard/layouts/DashboardLayoutStyles.js
src/components/response/Response.jsx
src/components/response/ResultSort.jsx

Change back button
